/**
 *  IWeaponryReportsService.idl
 *  Copyright (C) 2007-2011  GNUCITIZEN
 *  
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include "nsISupports.idl"
#include "nsIStringBundle.idl"

/* ------------------------------------------------------------------------ */

#include "IWeaponryWorkspacesService.idl"

/* ------------------------------------------------------------------------ */

interface IWeaponryReportsService;

/* ------------------------------------------------------------------------ */

[scriptable, uuid(f864bbb0-083e-11df-8a39-0800200c9a66)]
interface IWeaponryReportsService : nsISupports {
	attribute IWeaponryWorkspacesTableAPI issuesTable;
	
	/* -------------------------------------------------------------------- */
	
	void registerIssuesStringBundle(in nsIStringBundle bundle);
	
	void registerIssuesStringBundleUrl(in AString url);
	
	/* -------------------------------------------------------------------- */
	
	void unregisterIssuesStringBundle(in nsIStringBundle bundle);
	
	void unregisterIssuesStringBundleUrl(in AString url);
	
	/* -------------------------------------------------------------------- */
	
	AString generateIssueString(in AString name);
	
	/* -------------------------------------------------------------------- */
	
	AString generateIssueRecord(in AString item);
};

/*  GNUCITIZEN (Information Security Think Tank)
 **********************************************/