/**
 *  IWeaponryConsolesCommandLauncher.idl
 *  Copyright (C) 2007-2011  GNUCITIZEN
 *  
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include "nsISupports.idl"

/* ------------------------------------------------------------------------ */

interface IWeaponryConsolesCommandLauncherHandler;
interface IWeaponryConsolesCommandLauncher;

/* ------------------------------------------------------------------------ */

[scriptable, uuid(d2f42770-5591-11e0-b8af-0800200c9a66)]
interface IWeaponryConsolesCommandLauncherHandler : nsISupports {
	void write(in AString input);
	
	void writeLine(in AString input);
	
	void writeError(in AString error);
};

/* ------------------------------------------------------------------------ */

[scriptable, uuid(96eb8070-5591-11e0-b8af-0800200c9a66)]
interface IWeaponryConsolesCommandLauncher : nsISupports {
	boolean supportsConsole(in AString console);
	
	boolean supportsCommand(in AString command);
	
	/* -------------------------------------------------------------------- */
	
	void executeCommand(in AString console, in AString command, in AString args, in IWeaponryConsolesCommandLauncherHandler handler, [optional] in nsISupports context);
};

/*  GNUCITIZEN (Information Security Think Tank)
 **********************************************/